version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/product/php/app.dockerfile
    container_name: mockapi-php-prod
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  web:
    build:
      context: ./
      dockerfile: docker/product/nginx/web.dockerfile
    container_name: mockapi-nginx-prod
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /root/dhparam:/etc/ssl/certs
    ports:
      - 8088:80
      - 4443:443

  database:
    image: mysql:5.7
    container_name: mockapi-mysql57-prod
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

volumes:
  dbdata:
